### ISSUE TITLE
Having trouble using via API

### ISSUE THREAD

**Issue by altoiddealer** [Haoming02/sd-forge-couple#11]
Hello, first off I just want to say nice work on this, I love this extension :)

I used `http://127.0.0.1:7860/sdapi/v1/script-info` to get the json for Forge Couple, and set up my payload accordingly.

Either I'm overlooking something, or there's just something wrong with the formatting in the response... or something.

I'm no stranger to the API, I have multiple controlnets, Reactor, and layerdiffuse (omitted them for clarity)

If I delete the entire 'forge_couple' dict, I have no error.

`del payload['alwayson_scripts']['forge_couple']`

**Here's a copy of a payload which returns 422 error:**

>>>payload = {'prompt': '[high quality, best quality], 2people, blonde twintails, cyan eyes, white dress, looking at viewer, smile, blush {SEP} 2 people, white long hair, red eyes, black dress, looking at viewer, frown', 'width': 1280, 'height': 832, 'steps': 36, 'restore_faces': False, 'sampler_name': 'DPM++ 2M Karras', 'cfg_scale': 8, 'enable_hr': False, 'hr_upscaler': 'Latent', 'denoising_strength': None, 'hr_scale': 1.2, 'hr_second_pass_steps': 0, 'refiner_switch_at': 0.8, 'alwayson_scripts': {'forge_couple': {'args': [True, 'Horizontal', 'None', '{SEP}', 'Basic', {'headers': ['x', 'y', 'weight'], 'data': [['0:0.5', '0.0:1.0', '1.0'], ['0.5:1.0', '0.0:1.0', '1.0']]}]}}}

**Another example value returning 422:**

```
'forge_couple': {
    'args': [
        False, 
        'Horizontal', 
        'None', 
        '', 
        'Basic', 
        {'headers': ['x', 'y', 'weight'], 
        'data': [
            ['0:0.5', '0.0:1.0', '1.0'], 
            ['0.5:1.0', '0.0:1.0', '1.0']
        ]
    }
]
}
```

Please let me know, thanks!

**Comment by ramyma** [comment]
First of all for box definition you want to use `Advanced` (instead of `Basic`) for the mode arg.

Then for the mapping, use a list of points.

Something like:
```
'forge_couple': {
    'args': [
        False, 
        'Horizontal', 
        'None', 
        '', 
        'Advanced', 
        [
            ['0:0.5', '0.0:1.0', '1.0'], 
            ['0.5:1.0', '0.0:1.0', '1.0']
        ]
    }
]
}
```

You might need to pass in a different separator if an empty string doesn't work.

**Comment by altoiddealer** [comment]
For starters, I'm fairly certain that the arguments list much include a value for each parameter (in this case, 6 values).

Hence, why I include all the default values shown in the script-info response (aside from "Enabled: True")

I did just try what you suggested, as well as trying to omit the last item (maps dict), or using an empty dict, or formatting it as just a list of lists (as your example shows) - but these all still yield the 422 error.

Have you personally had a successful API response?

**Comment by ramyma** [comment]
This works for me:
```
"forge couple": {
              args: [
                // enable
                true,
                // direction
                "Horizontal",  //Vertical", //"Horizontal",
                // background
                "First Line"  //"First Line", // "None",
                // separator
                "<SEP>",
                // mode
                "Basic",  //"Basic", "Advanced"
                // mappings
                [],
              ],
            },
```

**Comment by altoiddealer** [comment]
From the API (http://127.0.0.1:7860/docs), I open the POST /sdapi/v1/txt2img module and use this value:

`{"prompt": "a guy", "width": 1024, "height": 1024, "steps": 33, "sampler_name": "DPM++ 2M Karras", "cfg_scale": 7, "alwayson_scripts": {}}`

If I use this value, I get 422 Error: "expecting value"

`{"prompt": "a guy", "width": 1024, "height": 1024, "steps": 33, "sampler_name": "DPM++ 2M Karras", "cfg_scale": 7, "alwayson_scripts": {"forge_couple": {"args": [True,"Horizontal","First Line","<SEP>","Basic",[]]}}}`

It's very strange, I believe this is exactly copy/paste what you are sending.

**Comment by ramyma** [comment]
You should at least have 3 prompts like `global prompt <SEP> left prompt <SEP> right prompt`

**Comment by altoiddealer** [comment]
I appreciate your following up on this.  I tried that verbatim (I understand the formatting)... same result

<img width="1069" alt="Screenshot 2024-04-06 142350" src="https://github.com/Haoming02/sd-forge-couple/assets/1613484/538502e8-6cee-476d-898a-788ecb1706fb">

**Comment by altoiddealer** [comment]
Here's a thought... is it possible that your script requires another script to also be enabled or something?

**Comment by ramyma** [comment]
The script name is `forge couple` without with a space instead of the underscore

**Comment by altoiddealer** [comment]
Tried that - same issue except the space character results in 'Unprocessable Entity'

`{"prompt": "global prompt <SEP> left prompt <SEP> right prompt", "width": 1024, "height": 1024, "steps": 33, "sampler_name": "DPM++ 2M Karras", "cfg_scale": 7, "alwayson scripts": {"forge couple": {"args": [True,"Horizontal","First Line","<SEP>","Basic",[]]}}}`

`Error 422: Unprocessable Entity`

**Comment by ramyma** [comment]
Give this payload a try
```
{"prompt": "global prompt <SEP> left prompt <SEP> right prompt","width": 1024,"height": 1024, "steps": 33, "sampler_name": "DPM++ 2M Karras", "cfg_scale": 7, "alwayson scripts": {"forge couple": {"args":["True","Horizontal","First Line","<SEP>","Basic",[]]}}}
```

**Comment by altoiddealer** [comment]
> Give this payload a try
> 
> ```
> {"prompt": "global prompt <SEP> left prompt <SEP> right prompt","width": 1024,"height": 1024, "steps": 33, "sampler_name": "DPM++ 2M Karras", "cfg_scale": 7, "alwayson scripts": {"forge couple": {"args":["True","Horizontal","First Line","<SEP>","Basic",[]]}}}
> ```

Thanks man, I was actually just in the process of reporting that this worked exactly - I just randomly tried closing the "True" in double quotes, and then the error changed to specifically say there was an error with the script name - and the space worked.

Thanks again!  Goddamn this stuff is super finicky.

**Comment by ramyma** [comment]
Actually I noticed you were had always on misspelled; it should be with an underscore.
I updated my previous comment.
This is the right form:
```
{"prompt": "global prompt <SEP> left prompt <SEP> right prompt","width": 1024,"height": 1024, "steps": 7, "sampler_name": "DPM++ 2M Karras", "cfg_scale": 7, "alwayson scripts": {"forge couple": {"args":["True","Horizontal","First Line","<SEP>","Basic",[]]}}}
```

**Comment by ramyma** [comment]
Actually I noticed you had alwayson_scripts misspelled; it should be with an underscore.
I updated my previous comment.
This is the right form:
```
{"prompt": "global prompt <SEP> left prompt <SEP> right prompt","width": 1024,"height": 1024, "steps": 7, "sampler_name": "DPM++ 2M Karras", "cfg_scale": 7, "alwayson scripts": {"forge couple": {"args":[true,"Horizontal","First Line","<SEP>","Basic",[]]}}}
```

**Comment by altoiddealer** [comment]
The key name including a space inside it, is very unusual and problematic... I've been working with yaml and python for a year now, and this is the first time I'm personally trying to deal with a key name with a space in it.

**Comment by altoiddealer** [comment]
Here's how I resolved it in my python script...

`payload['alwayson_scripts']['forge couple'] = payload['alwayson_scripts'].pop('forge_couple')`

**Comment by ramyma** [comment]
I'm not sure what's the problem you're facing. You can use dict keys with spaces in python; it's not ideal, but it works nonetheless.
