### ISSUE TITLE
Alt "{SEP}" method not working as expected (or not at all?)

### ISSUE THREAD

**Issue by altoiddealer** [Haoming02/sd-forge-couple#12]
Hello, thanks again for bearing with me on the last issue and helping me get that resolved for API usage.

I've been experimenting with the settings to use an alternate separation (not newlines), and as far as I can tell it just doesn't actually work.  Otherwise, I completely misunderstand the intention / usage.

I imagine the reason this setting exists is so users are not required to use new lines in their prompts.
Yet, you currently have only 1 example usage of "{SEP}" method... with 5 new lines in it.

<img width="636" alt="author" src="https://github.com/Haoming02/sd-forge-couple/assets/1613484/04adc0cc-3db9-4f30-acd8-e93804ee57f0">

Are new lines required in all cases, or not?  Or am I missing something?

---

## I cannot get a successful generation using an alternate separator method.

<img width="1219" alt="SEP" src="https://github.com/Haoming02/sd-forge-couple/assets/1613484/561283ab-ed16-4433-8a43-151eb6ac537f">

<img width="1216" alt="SEP2" src="https://github.com/Haoming02/sd-forge-couple/assets/1613484/fc71568f-aee0-422f-a047-51a1e370857a">

### NOTE: I've tried many different setting combinations, including `Global Effect: None`

---

## I can only get success with new lines.

<img width="1236" alt="newline" src="https://github.com/Haoming02/sd-forge-couple/assets/1613484/864a8701-bb1a-4f8e-923b-4cf7651ff6d0">

**Comment by ramyma** [comment]
The separator value replaces the new line; you'd use the defined separator text to split each prompt.

Sometimes the seed plays a role, if so, you can try a wider aspect ratio.

![image](https://github.com/Haoming02/sd-forge-couple/assets/14105815/22a18055-c8ce-4a7f-a698-ef8d55f06940)

![image](https://github.com/Haoming02/sd-forge-couple/assets/14105815/6d128a52-0e36-48cc-ba45-b0d04561cffc)

**Comment by altoiddealer** [comment]
Are you able to use it with a more complex prompt, such as all the other examples?  The results you shared looked like results I would get with the extension disabled.

**Comment by ramyma** [comment]
Works fine, sometimes it depends on the seed an aspect ratio like I mentioned.

![image](https://github.com/Haoming02/sd-forge-couple/assets/14105815/482bd3a2-b432-4ae6-8497-efc73087d310)

**Comment by altoiddealer** [comment]
Thanks for following up.

Honestly, I'm still not convinced that the extension is actually working at all with the {SEP} method.

Have you tried reusing the same seed, but with the extension disabled?

<img width="1680" alt="1" src="https://github.com/Haoming02/sd-forge-couple/assets/1613484/8f404ef3-8615-41de-92e6-cad5ab624655">

<img width="1679" alt="2" src="https://github.com/Haoming02/sd-forge-couple/assets/1613484/7933daa9-6369-4d22-9dd7-37bd3c65dada">

---

<img width="1681" alt="3" src="https://github.com/Haoming02/sd-forge-couple/assets/1613484/61a244f1-52ac-4910-ae76-20b17799522e">

<img width="1684" alt="4" src="https://github.com/Haoming02/sd-forge-couple/assets/1613484/7e2a54d9-0874-46b1-83fe-bd4655d74ab8">

**Comment by ramyma** [comment]
Check the terminal, sometimes there's an error and the extension doesn't do any difference in this case; it fails silently and passes the generation through to the next step.

**Comment by altoiddealer** [comment]
`[Couple] Not Enough Lines in Prompt...`
`[Couple] Not Enough Lines in Prompt...`
`[Couple] Not Enough Lines in Prompt...`
Forever and ever, unless I do not use the {SEP} method

<img width="1674" alt="Screenshot 2024-04-07 161851" src="https://github.com/Haoming02/sd-forge-couple/assets/1613484/c7479f47-366c-41db-bfcb-bf4b6c9f6656">

**Comment by ramyma** [comment]
Try disabling other extensions, make sure you have the latest version of Forge and Forge Couple.
It probably would be one of those things.

**Comment by altoiddealer** [comment]
So, I added print statements in your script and found the following:

If the "separator" value is enclosed in brackets such as `{SEP}`, the brackets are actually not included in the "separator" value, so it will never find it in the prompt.


The feature actually works - it just can't be enclosed with curly brackets, and maybe some other special characters, idk.

But it definitely does not work with curly brackets.

**Comment by altoiddealer** [comment]
Alllllrighty, you were correct again!

The [Dynamic Prompts](https://github.com/adieyal/sd-dynamic-prompts) extension uses curly brackets for its syntax, so it is apparently stripping them out of the prompt.  When I disable the extension, "{SEP}" works.

In any case, values without curly brackets works though.
