### ISSUE TITLE
Suggestion: Try to imitate (or 100% copy) Regional draw mode from Multidiffusion

### ISSUE THREAD

**Issue by altoiddealer** [Haoming02/sd-forge-couple#15]
Heya, I've been meaning to suggest this... and I was reminded by the fact that you actually just pushed a "Draw the regions" update.

[The Multidiffusion extension](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111) for A1111 has a very sweet "draw your regions" feature in its Regional Prompt Control panel.

I'm just mentioning this in case you haven't seen it before... if you have not, I strongly recommend you check it out.

<img width="733" alt="Screenshot 2024-04-10 223204" src="https://github.com/Haoming02/sd-forge-couple/assets/1613484/ead8629a-5de9-4612-b150-d09117d2b888">

**Comment by Haoming02** [comment]
Guess I really should merge #14

**Comment by altoiddealer** [comment]
> Please give the [draggable-regions](https://github.com/Haoming02/sd-forge-couple/tree/draggable-regions) branch a try
> 
> Implementation is not exactly the same as `MultiDiffusion` ~for better or for worse~

Unfortunately, it seems quite buggy, and I much prefer the current implementation in the main branch.

- The ability to resize the boxes with your cursor is the most important aspect.
- Recreating the boxes every time you click/drag isn't terrible (current behavior of main branch).  It's just a shame you need to click the "Draw new box" button every time.
- This draggable-regions branch seems to sacrifice everything in order to make the boxes 'moveable'.  Am I missing something?  It seems impossible to create new boxes or scale them or anything using the cursor.
- It's also very confusing that clicking on a "Row" toggles the selection ON/OFF for its Mask Box.  When clicking on a Row, it should toggle the selection ON if it is currently OFF... the selected Mask should only be toggled OFF when selecting a different Row.

**Comment by Haoming02** [comment]
I suggest checking the document first, since well, all of what you said are already mentioned
https://github.com/Haoming02/sd-forge-couple/tree/draggable-regions?tab=readme-ov-file#advanced-mapping

**Comment by altoiddealer** [comment]
> I suggest checking the document first, since well, all of what you said are already mentioned https://github.com/Haoming02/sd-forge-couple/tree/draggable-regions?tab=readme-ov-file#advanced-mapping

Read the Readme!? haha

Welp, you got me there.  And Now that I understand the usage, it is very nice.

You should add those very important control details in the UI somewhere... otherwise, people like me who think this stuff is all self-explanatory will be scratching there heads

**Comment by Haoming02** [comment]
> You should add those very important control details in the UI somewhere

- The row-control buttons show a tooltip when hovered *(like other Webui built-in ones)*
- The region box shows the move / resize cursor when hovered

Though yeah, I'll probably add like a triangle or something at the bottom right corner

**Comment by arcusmaximus** [comment]
If a UI has up and down arrows above a grid, I think most users will assume they mean "move up/down" and not even bother looking at the tooltips. Instead, they'll wonder why there's no "add" button :p

Also, there's no reason for only allowing resize using the bottom right corner. Both MultiDiffusion and my fork let you drag any corner (or side), as users would expect.

@altoiddealer: I invite you to try [my version](https://github.com/arcusmaximus/sd-forge-couple) of a draggable box UI as well. It should be understandable without reading a manual, and makes it easier to see which prompt belongs to which region ([screenshot](https://github.com/Haoming02/sd-forge-couple/issues/2#issuecomment-2046083573)). In addition, it doesn't require you to cover the whole image with regions.

(I previously created a pull request to merge my UI into this repository and make it official, but Haoming02 sadly doesn't want to merge it.)

**Comment by Haoming02** [comment]
At least the main feature, the actual mapping, works now, while those can be added/changed in later versions. :P

Btw, the last time I tried it, both your fork and MultiDiffusion suffer from the same problem: When 2 masks are on top of each other, you can't really choose which one to move, right?

And ah yes, TypeScript, the language where you need thousands of lines across muiltiple files just to do something that, realistically, only requires few hundred lines in JavaScript... I'll learn TS someday, but that day is not today. *(esp. when my main job isn't even web dev)* Sorry.

**Comment by Haoming02** [comment]
Full 8 Directional Resizing has been implemented~

**Comment by Haoming02** [comment]
Hints for the corresponding prompt has been implemented~

**Comment by arcusmaximus** [comment]
If you click a prompt textbox in my fork, the corresponding region will be brought to the front. If you click a partially overlapped region, it will be brought to the front. And if the corner/side you want to drag isn't overlapped, you can immersively start dragging without having to select anything.

What's more, if you click a region, it'll automatically put focus on the corresponding prompt textbox. No need to count rows and find the matching line in the main prompt.

Region prompts are stored in the infotext together with the positions/sizes. There's a small bug where you first have to switch to the Advanced tab and only then load the infotext into the UI - but other than that, you can restore all the information from both an image and from your last generation. The latter doesn't work in the current official version btw.

Typescript isn't hard, and my code would've barely been shorter if I hadn't used it. In fact, it saved me time by giving me accurate autocomplete and catching problems before testing in the browser. Sure, it's not *needed* for a small project like this, but it does help.

Anyway, good to see improvements being made, even if it's just replicating what's already there.

**Comment by altoiddealer** [comment]
@arcusmaximus  I still haven’t tested - I think ideally there would be a means to select a mask that is completely covered… are you able to if you toggle the visibility of a higher layer?  Or will the invisible layer still interfere with selecting/manipulating a lower one?

**Comment by MoreColors123** [comment]
I don't really want to chime in on the language topic because i'm not by any means a dev but just your casual tester :D
I just tested the draggable-regions branch for a bit and it works well. (SDXL Lightning)

![grafik](https://github.com/Haoming02/sd-forge-couple/assets/131474336/f15a5bf7-e498-4c5c-855e-ed2d427a7f7c)
![00013-3988159980](https://github.com/Haoming02/sd-forge-couple/assets/131474336/d8f372a5-83fc-4f0b-8239-87bbf55539ec)

**Comment by MoreColors123** [comment]
What i just found out is that you always need an extra generation for it to apply the last change in a regional prompt. So i think something is gone wrong. For example: i change the prompt from "jungle" to "desert" and it doesn't apply it in the next generation, only in the one afterwards.

**Comment by Haoming02** [comment]
If the problem is about their fork, please open an issue on their fork instead :)
If the problem also happens here, do open a new issue~

**Comment by MoreColors123** [comment]
Oh god i totally mixed them up, all those branches :] Sorry and thanks for your work

**Comment by arcusmaximus** [comment]
@MoreColors123 That's because the canvas only got updated with the new prompt when clicking outside the textbox. I made it update on every keypress instead, which fixes the problem.
