### ISSUE TITLE
Auto-update aspect ratio for region canvas

### ISSUE THREAD

**Issue by arcusmaximus** [Haoming02/sd-forge-couple#21]
~~It would be easier to set up regions if the aspect ratio of the canvas matched that of the image you're about to generate.~~

While it's already possible to make the canvas size match the generation size, users need to click the "Preview Mapping" button for this. They're unlikely to use this button for anything else, however, so (at least in my experience) it's easy to miss.

**Comment by Haoming02** [comment]
It already does though?

**Comment by arcusmaximus** [comment]
Right - if you click "Preview Mapping", which I didn't think to click anymore because the mappings get previewed automatically now. Also, it's doesn't work in img2img if you select "Resize by" instead of "Resize to".

Most userfriendly would be for the extension to auto-detect changes in the Forge UI.

**Comment by Haoming02** [comment]
Mappings get previewed automatically cause any input triggers the clicking of Preview Mapping button, thus loading the resolution.

Just say when it does not update instead.

**Comment by arcusmaximus** [comment]
As above, it was a misunderstanding on my part. I didn't see a button to update the canvas size, and didn't bother clicking "Preview mappings" because the mappings were already previewed.

I updated the issue description.

**Comment by Haoming02** [comment]
I just tested your fork, and found the same problem I'm currently facing as well:
The `onchange` event is not fired when the resolution is changed by the Webui, *(**eg.** the `Switch width/height` button or the `Send to ...` buttons)*

Does the `observer` thingy helps in this case?

**Comment by arcusmaximus** [comment]
The MutationObserver doesn't work, but it turns out that using the `input` event instead of `change` does. Updated my fork accordingly.

**Comment by Haoming02** [comment]
Mapping now resizes based on `sliders`, `buttons`, `image upload`, both `resize to` and `resize by`, and `send to` buttons
