### ISSUE TITLE
Allow setting a background image in the canvas

### ISSUE THREAD

**Issue by arcusmaximus** [Haoming02/sd-forge-couple#22]
Being able to set a custom background image in the canvas is useful when you're doing img2img or using e.g. ControlNet Canny. Bonus points for having a button that retrieves the current img2img input image without the user having to save and reupload it.

See [this code](https://github.com/arcusmaximus/sd-forge-couple/blob/draggable-box-ui/typescript/BoxCanvasControl.ts#L157C17-L157C34) for an example of how it can all be done without using sluggish Gradio (lines 157 to 216).

**Comment by superfid2006** [comment]
Nice, came here since I wanted to ask for just this. This functionality in Regional Prompter was very helpful for i2i, seeing the same way to draw the rectangles for advanced regional control in Forge Couple would be great.

**Comment by arcusmaximus** [comment]
If you want to use background images already now, you can use [my fork](https://github.com/arcusmaximus/sd-forge-couple) of this extension.
