### ISSUE TITLE
Firefox - Changing weights not possible

### ISSUE THREAD

**Issue by MoreColors123** [Haoming02/sd-forge-couple#23]
When I click the weight box in Firefox, in order to change the value, it is resulting in an empty box. In Chrome it is working though.
The new value just disappears:
![grafik](https://github.com/Haoming02/sd-forge-couple/assets/131474336/e5187d83-7a80-4da6-9123-065a1b99ea5d)

**Comment by Haoming02** [comment]
Should I just add "incompatible with Firefox"? #9

**Comment by MoreColors123** [comment]
If i know it, i wouldn't mind. I know that browsers can be a PITA

**Comment by arcusmaximus** [comment]
FWIW, it works on Firefox for me. Still awkward having to double-click though.
