### ISSUE TITLE
Suggestions for UI

### ISSUE THREAD

**Issue by MoreColors123** [Haoming02/sd-forge-couple#24]
Hi, i very much appreciate your work, and this is a fantastic extension, i must say. having lots of fun.

Still the UI is not perfect and sometimes not very user friendly at all. I can think of the following suggestions:
- **add the prompt to the table**... thats a big one and would improve it so much obviously!
- make it **more compact** on the top. reduce spacings, put the "reset to default mappings button" somewhere up top. scrolling around too much already :)
- put "delete row"-button next to row
- get rid of the down and up arrows (which are mistaken for something else anyway) and add a "new region" button. I don't care at which position the row is added at all, even more so if i need to keep the prompt lines assigned correctly anyway. I will rather just move the prompt to the correct line than find the correct row and insert a new row next to it. 
- get rid of the "coordinates", as i don't care about them as a user and will not input them anyway.
- use the auto1111 ui element with arrows for weight selector (like in batch size), if possible

**Comment by Haoming02** [comment]
> add the prompt to the table

I'd rather not making it more cluttered, or you could say, less **compact**. I prefer prompts stay at where prompts should be.

> put the "reset to default mappings button" somewhere up top

But it's already at top though? wdym

> get rid of the "coordinates", as i don't care about them as a user and will not input them anyway.

As someone with OCD, I do :P

**Comment by MoreColors123** [comment]
haha :D fair point. 
i just threw this together in photoshop, i find this much much compact and cleaner. the buttons could be textbuttons too, i think.
![grafik](https://github.com/Haoming02/sd-forge-couple/assets/131474336/a392c16a-4a4e-448f-8d39-5120b1b24890)

**Comment by arcusmaximus** [comment]
Being able to type exact region positions/sizes would make sense if the image would exactly follow them. However, it doesn't - regions are just a vague guideline and their prompts bleed outside their boundaries. So I'm also not sure there's much point in showing all these precise numbers.

Region prompts: the grid already shows these on hover to make it easier to see which prompt belongs to which region. I'd say the logical next step is to turn these tooltips into textboxes. Less scrolling, less frustration.

**Comment by ostap667inbox** [comment]
1. Fields with prompts would really improve usability. You don't need to add them to the table with coordinates, let it be a separate table with prompts below. Only table rows should be highlighted with the same color gradient to avoid confusion. And under the table there is a button "copy result to the main prompt window". Why it's important: Now the prompt window is very separate from Forge Couple. When you have 6-7 rows, it's very hard to perceive which row belongs to which zone. So this would really be very handy.
 It doesn't have to be a mandatory part of the workflow - someone who is more comfortable doing prompt manually in the main prompt window can keep doing it.
2. And please, please, please, please consider making a version of your excellent plugin for A1111 as well. Regional Prompter, which is there now, can be shown in UI/UX tutorials as an example of complete lack of usability. When I try to use it, I'm constantly afraid of causing Satan, an earthquake in Southeast Asia or something like that, it burns the place I'm sitting on so much :)

**Comment by ostap667inbox** [comment]
> That's why I add the tooltip when hovering though. Does it not work?

Tooltip is very-very good. However, the prompt editing process itself is still on the other side of the interface. This is purely a matter of perception. It is not such an important part of the workflow that it would be difficult to work without it. No. However, it is still one of the good ideas for further development of the plugin.
Only, I repeat, if it is planned to be implemented someday, it would be better to make the table with prompts separate from the table with coordinates (I recommend it as a UI designer). This separation will improve perception and make the process less cumbersome for those who find it more convenient to write prompts in the main window. A good idea in this case would also be to highlight the area where the cursor is currently in focus in the prompt field.

**Comment by Haoming02** [comment]
Do people actually go back and forth between the mappings and the prompt constantly?

Cause in my mind, you just finish writing your prompt, then go adjust the regions, or vice versa. So that's why I don't see the point in also being able to edit the prompt down there...

**Comment by ostap667inbox** [comment]
> Do people actually go back and forth between the mappings and the prompt constantly?

That's right. They look at the zones and they think of an addition to the prompt, go back to the zones to correct the position, look at the intermediate result of the generation and repeat the process again, move something, change something in the text, etc - that's why it's called 'workflow', because it 'flows and changes' :)

**Comment by Haoming02** [comment]
How about, when showing the hovering tooltip, press `Enter` to enable prompt-editing (on the tooltip), press `Enter` again to finish editing?

**Comment by MoreColors123** [comment]
This is an idea in the right direction. Is it by any chance simply possible to add an icon on the corner of a region box to edit the prompt? This would be the most direct solution. 

I honestly think every option to stay on the bottom of the screen is good. I too am constantly changing regions AND prompts.  Hence, scrolling up and down, and not remembering which line corresponds to which region, makes me insane. :D

Then maybe, while we're at it: to hide the table can you add a simple menu for it like this (see adetailer, controlnet, and many more). 
![grafik](https://github.com/Haoming02/sd-forge-couple/assets/131474336/2fd3b5c7-06dc-4a4d-a103-0474480a72b5)
And then I think it is improved by a lot again!

**Comment by arcusmaximus** [comment]
> How about, when showing the hovering tooltip, press Enter to enable prompt-editing (on the tooltip), press Enter again to finish editing?

That would make it the first application I've ever seen with editable tooltips heh. I doubt any user is going to figure that out on their own.

Of course, you could add another entry to the readme. But consider this...
UI wise, there's barely anything to this extension. There are boxes, prompts, and weights - that's all. It could be so simple that users don't even need a readme. Why make it so much more complicated than it needs to be?

Having position/size numbers in the grid doesn't seem useful. Having prompts in the grid does. So... replace the numbers by the prompts, and you have two improvements in one go.

> Then maybe, while we're at it: to hide the table can you add a simple menu for it

This issue already has quite a few different topics 😅. Might be best to start creating separate issues instead.

**Comment by Haoming02** [comment]
btw, another question, for the mappings, which one do y'all prefer: 

- having a height limit, with a scroll bar on the side *(current implementation)*
- letting the entries stack infinitely *(like <ins>arcus</ins>' fork)*

**Comment by ostap667inbox** [comment]
> * letting the entries stack infinitely _(like arcus' fork)_

I find this option more convenient

**Comment by Haoming02** [comment]
Please give the [`revamp`](https://github.com/Haoming02/sd-forge-couple/tree/revamp) branch a try!
