### ISSUE TITLE
Question about new Advanced mapping.

### ISSUE THREAD

**Issue by E2GO** [Haoming02/sd-forge-couple#25]
How to use Global Effect now? It's not visible in advanced tab. Just use base prompt window for it and at mapping regions only for regions?..

**Comment by Haoming02** [comment]
If you want global effect, simply add a region that covers the entire image

**Comment by E2GO** [comment]
So I shouldn't use main prompt at all? What effect it causes if I do?

**Comment by Haoming02** [comment]
wdym

"Global Effect" is only for **Basic** mode. In **Advanced** mode, you set up your own mappings. Hence why if you want an effect that is global, you add an try that is global.

**Comment by E2GO** [comment]
kk, got it! Thanks for quick response
