### ISSUE TITLE
how to create 1 woman kissing his son?

### ISSUE THREAD

**Issue by timmyhk852** [Haoming02/sd-forge-couple#31]
I tried, but the woman became very short as if she's a girl to kiss the son

**Comment by Haoming02** [comment]
<p align="center"><img src="https://github.com/Haoming02/sd-forge-couple/assets/73768377/e4964e11-bf26-438f-b98c-202f8d7d91dc" width=512></p>

```
a cinemtaic photo of a mother hugging her son, cheek-to-cheek, warm, household
a mother, standing, leaning forward, living room
a boy, child, standing, on floor, crying, living room
```

<p align="center"><img src="https://github.com/Haoming02/sd-forge-couple/assets/73768377/4c1de025-9d39-4453-81d3-8a119f9b965f" width=768></p>

**Comment by timmyhk852** [comment]
I dont know why most of the time, it doesnt work as intended.
![screencapture-127-0-0-1-7860-2024-04-25-21_00_55](https://github.com/Haoming02/sd-forge-couple/assets/132486967/bf211277-d928-4056-ae1a-86865630fae8)
![screencapture-127-0-0-1-7860-2024-04-25-21_04_56](https://github.com/Haoming02/sd-forge-couple/assets/132486967/5336c79f-5561-42e7-b545-d717dd6e0f36)

**Comment by ostap667inbox** [comment]
> I dont know why most of the time, it doesnt work as intended.
Try to use other checkpoints for photo generation. Not a Pony type (it is deformed SDXL fork specially for anime and it has a specific set of trigger words).

**Comment by Haoming02** [comment]
Yeah, I also tried with other anime checkpoints before, but wasn't able to get it correctly
