### ISSUE TITLE
Generating 4+ unique characters

### ISSUE THREAD

**Issue by Zboy18** [Haoming02/sd-forge-couple#34]
I am having difficulty generating 4 or more different characters in a sceen the characters often bleed prompt traits into one another 
example prompt with first line global effect active 
score_9, score_8_up,4girls,dawn(pokemon),blue hair,white hat,pink scarf,night time,forest,ambient lighting,
4girls,may(pokemon),brown hair,red bandana,belt,black shorts,
4girls,serena(pokemon),brown hair,red hat,skirt,shirt,suspenders,
4girls,hilda(pokemon),brown hair,white hat,blue shorts,vest,white shirt,

Am I doing something incorrectly?

**Comment by Haoming02** [comment]
```
score_9, score_8_up, 4girls, standing, side-by-side, night time, forest, ambient lighting
4girls, dawn \(pokemon\), blue hair, white hat, pink scarf
4girls, may \(pokemon\), brown hair, red bandana, belt, black shorts
4girls, serena \(pokemon\), brown hair, red hat, skirt, shirt, suspenders
4girls, hilda \(pokemon\), brown hair, white hat, blue shorts, vest, white shirt
```

<p align="center"><img src="https://github.com/Haoming02/sd-forge-couple/assets/73768377/4b10b627-95a8-42b1-be6c-6d57614c104e"></p>

1. If you have **Global Effect** active *(`First Line` in my case)*, you need to put it in an extra line
2. Use `\` to escape the `(` and `)`. Otherwise, they will be interpreted as emphasis instead.

**Comment by Zwilliam** [comment]
I see I will give that a try thanks for the help

**Comment by Zboy18** [comment]
I still end up in some scenarios where it generates extra characters.
![00208-820128344](https://github.com/Haoming02/sd-forge-couple/assets/3981670/048c0dc5-9ac8-4207-a925-c8e3270b4923)
![00209-820128345](https://
![00210-820128346](https://github.com/Haoming02/sd-forge-couple/assets/3981670/38fe3102-7f4a-4af3-9f44-8e7a1de5e486)
github.com/Haoming02/sd-forge-couple/assets/3981670/282cc956-b808-4f72-a2c9-a7c303379bee)

**Comment by Haoming02** [comment]
Yeah, it doesn't just work every single time unfortunately...

Adding an `OpenPose` **ControlNet** helps a bit in my experience
