### ISSUE TITLE
How do I write prompt if I want to generate characters of different genders?

### ISSUE THREAD

**Issue by Max-Liu** [Haoming02/sd-forge-couple#35]
Here's what I'm writing right now:
[rating: general,high quality],
2boys, male focus, vegeta, dragon ball,blonde hair,
2girls, raiden shogun, genshin impact,

But the results are not stable

**Comment by Haoming02** [comment]
So... did you get it?

**Comment by Max-Liu** [comment]
@Haoming02 it should be 
[rating: general,high quality],
1boy, male focus, vegeta, dragon ball,blonde hair,
1girl, raiden shogun, genshin impact,

right? but the results are also not stable 😄

**Comment by Haoming02** [comment]
```
[high quality, best quality], 1boy 1girl, standing, side-by-side
1boy, 1girl, vegeta, \(dragon ball\)
1girl, 1boy, raiden shogun, \(genshin impact\)
```

<p align="center"><img src="https://github.com/Haoming02/sd-forge-couple/assets/73768377/9f81c33a-5e5c-4959-9d64-9840f83dca60"></p>

~~Apparently, **animagineXLV3** doesn't know Dragon Ball characters?~~

**Comment by Max-Liu** [comment]
![image](https://github.com/Haoming02/sd-forge-couple/assets/1518955/f9553f49-906c-4f27-ad98-7d3a297abdf9)
yeah, i am using animagine-xl-3.1, your prompt is much better, thx!

**Comment by Max-Liu** [comment]
how about 3 people? @Haoming02 H

[high quality, best quality], 1boy 2girls, standing, side-by-side
1boy, vegeta, \(dragon ball\)
2girls, raiden shogun, \(genshin impact\)
2girls, amber \(genshin impact\), genshin impact

is this correct？The results are not very stable

![image](https://github.com/Haoming02/sd-forge-couple/assets/1518955/843d2132-3e0e-4cc2-887b-adeaf07e4310)
![image](https://github.com/Haoming02/sd-forge-couple/assets/1518955/9f5afaec-7e45-47cf-9144-8696f026eeb8)
![image](https://github.com/Haoming02/sd-forge-couple/assets/1518955/9a240a29-26de-41f8-a2fd-58ae065e5b6a)

**Comment by Haoming02** [comment]
Yeah...

In these cases, using **ControlNet** such as `OpenPose` can help a bit
