### ISSUE TITLE
[QUESTION] Possibility of port to SDNext?

### ISSUE THREAD

**Issue by Bercraft** [Haoming02/sd-forge-couple#36]
It would be a great addition to SDNext as of now except for a script there is nothing like this in the extensions.
Thank you best regards.

**Comment by Haoming02** [comment]
Does [Regional Prompter](https://github.com/hako-mikan/sd-webui-regional-prompter) not work for `SD.Next`?

Also, just like `Automatic1111`, porting wouldn't be possible unless they also change the backends.

**Comment by Bercraft** [comment]
OK i understood.
Your plugin is much more precise and user friendly.
Thank you.
