### ISSUE TITLE
Not getting desired results with specific prompt

### ISSUE THREAD

**Issue by Vektor8298** [Haoming02/sd-forge-couple#39]
Hello, I find this extension a lifesaver, but due to the model I use, and the way prompts should be made, I am having issues with prompt adherence. The model I use needs the prompt to start with `best quality, masterpiece, score_9, score_8_up,source_anime,2.5d, BREAK` and make a new line, and then prompt what you would normally do. This is where issues start, since images don't follow my prompt correctly.
https://imgur.com/a/sguB0Qp

**Comment by Haoming02** [comment]
I also use `Pony` models, and this works perfectly fine with it.

Just set the `score_` line as the global. Or don't make it into a new line.
