### ISSUE TITLE
Advanced mapping broken?

### ISSUE THREAD

**Issue by sashasubbbb** [Haoming02/sd-forge-couple#40]
For some reason on latest version of extension advanced map doesn't appear on Forge.
![Screenshot at 07-14-37](https://github.com/Haoming02/sd-forge-couple/assets/60400449/a48b6a73-07e1-499e-b505-0588a7b07eef)
Not sure what could be the issue.
Reverting to 6032a72cfdda2e124768b8274ac63b1910776ec0 fixed region mapping window.

**Comment by Haoming02** [comment]
Latest commit ([e8e258e](https://github.com/Haoming02/sd-forge-couple/commit/e8e258e982a8d149ba59a4bc43b945467604311c)) seems to work fine for me

Is there any error?
