### ISSUE TITLE
Is the button option for pictures canceled?

### ISSUE THREAD

**Issue by tanglup** [Haoming02/sd-forge-couple#44]
![image](https://github.com/user-attachments/assets/8e8475b8-7007-466b-ba2e-16a1d640785c)

**Comment by tanglup** [comment]
Is the Advanced function cancelled?

**Comment by Haoming02** [comment]
> * Currently only the `Basic` mode works in Gradio 4

**Comment by tanglup** [comment]
> > * 目前该`Basic`模式仅适用于 Gradio 4

Meaning, only the old version of forge has advanced

**Comment by Haoming02** [comment]
是
