### ISSUE TITLE
If you turn on forge couple, you can't right-click on lora-prompt-tool.

### ISSUE THREAD

**Issue by githabtane** [Haoming02/sd-forge-couple#47]
Forge of Gradio 4  Branch=revamp
The update works fine, but again
The right-click menu will not be displayed with the combination of　[LoRA Model Prompt Tool](https://github.com/a2569875/lora-prompt-tool)+forge couple
It works if I remove forge couple from the extension

**Comment by Haoming02** [comment]
Seems like the new Gradio 4 image canvas keeps triggering the `change` event, causing other functions to get blocked...?

**Comment by githabtane** [comment]
thank you. It worked fine
