### ISSUE TITLE
Grid on Advanced Mode are not correct

### ISSUE THREAD

**Issue by kemefih** [Haoming02/sd-forge-couple#49]
Hi, there some buggy with the area you can drag are not match the canvas.
![image](https://github.com/user-attachments/assets/5986f162-d51c-4df8-b1cd-d6ae25aa5565)

**Comment by Haoming02** [comment]
Oh yeah, I can repro it too. 

Seems to only happen on the new Forge, and only when the resoluition width is large than height?

**Comment by Haoming02** [comment]
Should be fixed~
