### ISSUE TITLE
--cuda-stream option

### ISSUE THREAD

**Issue by githabtane** [Haoming02/sd-forge-couple#55]
Forge of Gradio 3
mask mode doesn't work properly

**Comment by Haoming02** [comment]
Uhh... any example?

The image in the README was generated on Gradio 3 Forge btw

**Comment by githabtane** [comment]
gpu rtx2070 super Pytorch 2.4.0+cu12.4 cudnn-windows-x86_64-9.3.0.75_cuda12
set COMMANDLINE_ARGS=--xformers --pin-shared-memory --cuda-malloc --cuda-stream --theme dark
forge commits bfee03d8d9415a925616f40ede030fe7a51cbcfd

**Comment by githabtane** [comment]
![スクリーンショット 2024-09-06 183204](https://github.com/user-attachments/assets/ae15b1db-a920-4efa-9347-1fd9b2d611e8)

**Comment by githabtane** [comment]
set COMMANDLINE_ARGS=--xformers --pin-shared-memory --theme dark

![スクリーンショット 2024-09-06 183609](https://github.com/user-attachments/assets/bd371287-e878-4404-94c9-5f5812a120f8)

**Comment by Haoming02** [comment]
Seems like you sovled it?

**Comment by githabtane** [comment]
Masks cannot be drawn with the --cuda option

**Comment by Haoming02** [comment]
Even after clicking `Create Empty Canvas`?

**Comment by githabtane** [comment]
Yes, that's right. The cursor doesn't even appear

**Comment by Haoming02** [comment]
> The cursor doesn't even appear

After clicking `Create Empty Canvas`, try adjusting the brush size *(the pen-shaped button on the right)*

**Comment by githabtane** [comment]
Even if you press Create Empty Canvas, it will be canceled immediately and a hand-shaped cursor will be displayed.

**Comment by Haoming02** [comment]
> try adjusting the brush size

Have you tried this?

**Comment by githabtane** [comment]
Yes, I tried but the round cursor does not appear

**Comment by Haoming02** [comment]
> try adjusting the brush size

Also just in case, you have to actually drag the slider, not just clicking on the button. At least that's what worked for me...

**Comment by githabtane** [comment]
There is no problem with microsoft ege. thank you

**Comment by Haoming02** [comment]
Oh yeah, I'm using Edge as well. 

Were you using Firebox by any chance?

**Comment by githabtane** [comment]
chrome

**Comment by Haoming02** [comment]
Huh, that's even more bizarre now XD

Aren't both Edge and Chrome based on Chromium?

**Comment by githabtane** [comment]
microsoft egeで試した後、chromeでも動作するようになりました。不思議です。
