### ISSUE TITLE
[Feature Request] Mask Mode support upload mask

### ISSUE THREAD

**Issue by realisticdreamer114514** [Haoming02/sd-forge-couple#56]
Congrats on reverse-engineering [hako-mikan/sd-webui-regional-prompter](https://github.com/hako-mikan/sd-webui-regional-prompter) for sd forge! Now 1 feature regional prompter has is a work-around to upload masks in their mask mode, so I can work in paint.net instead of squinting at the gradio canvas inside the extension. 
Maybe you should copy that one: https://github.com/hako-mikan/sd-webui-regional-prompter?tab=readme-ov-file#mask-regions-aka-inpaint-experimental-function
Regional prompter also assigns a fixed color for each layer/region to help painting in external image editors, but it's hard to figure out the right color to use once there are more than a handful of them. Find a way to upload a BW mask to override the layer selected instead.

**Comment by Haoming02** [comment]
> Congrats on reverse-engineering [hako-mikan/sd-webui-regional-prompter](https://github.com/hako-mikan/sd-webui-regional-prompter) for sd forge!

I did reference it, among many similar extensions, such as [ashen-sensored/stable-diffusion-webui-two-shot](https://github.com/ashen-sensored/stable-diffusion-webui-two-shot), for how the UI should look. But I didn't reverse-engineer anything really. I coded the UI myself ~~through some real jank JavaScript~~. 

If you meant the functionality, it's ported from a ComfyUI Node as mentioned in the [Special Thanks](https://github.com/Haoming02/sd-forge-couple?tab=readme-ov-file#special-thanks).

> upload masks in their mask mode

Was in my **To Do** indeed. Now implemented in the latest commit~

> a way to upload a BW mask to override the layer selected instead

This is also now possible~

**Comment by realisticdreamer114514** [comment]
I was just half joking... Gonna tell you another request in a new issue, feel free to close this one.
