### ISSUE TITLE
Full numbers instead of 0.x? And maybe weigts to the layers? Sometimes it doesn't read layers from prompt.

### ISSUE THREAD

**Issue by maniac-0s** [Haoming02/sd-forge-couple#58]
So far loving the extension. Always struggled with regional prompter because of their awkward UI but this one here is very simple to use.

Although I'd have a few suggestion / feature requests.

First, it would be nice if we could enter the layer sizes in full numbers. Typing 33 for 33% is much easier than 0.33. A minor issue but should also be relatively simple to implement.

Next issue is that I sometimes need to reroll alot. Like 3 out of 4 or 4 out of 5 it does not generate a couple instead if would generate 1girl/1guy or 2 guys and no girl and so on, mixed together (like she is wearing half a dress and half a suit). I don't know if adding weights to layers like (include this and that is most important, the planet in the sky is not that important (could also inpaint afterwards if I need to).

I don't know if there are any ticks to use this better, so far haven't found any.

Last but not least, another usability issue: Sometimes it doesn't read the \n as a new layer. For instance I type in one prompt, enter, next prompt, enter, a background. Then I select "last" as global but it still would tell that there "numbers of couples and mapping is not the same". I then need to go to advanced and add another layer, but sometimes that's confusing. Would be cool if we had a reload button that reads the prompt and generates layers from the \n in the input. It is cool that it tries to read layers from the prompt tho in general and I love that I don't necessarily need a BREAK and AND or ADDCOL etc. in the prompt like with LC.

**Comment by realisticdreamer114514** [comment]
For the last one there's this https://github.com/Haoming02/sd-forge-couple?tab=readme-ov-file#couple-separator 
I use `\n*\n` which means
`[layer 1 prompt]`
`*`
`[layer 2 prompt]`
are separated by [newline]*[newline] instead of just a single newline. Doing this it doesn't ignore any newline you use to separate layers, because by then a simple newline won't do anything. Let's see if this helps, or else its a real coding problem
(Besides you won't accidentally create new layers by hitting Enter this way)

**Comment by realisticdreamer114514** [comment]
About the 2nd suggestion, not sure if the extension supports dividing negative prompts like what regional prompter already does, so that it's easier to specify the tokens/tags you don't want to appear in each layer, like 1boy here and 1girl there.

**Comment by maniac-0s** [comment]
Ok thanks I will try this with the double \n

About the second issue, yes it doesn't take negative into account, and thus I only use negative for what I want to negative in general (like score tags for pony, NSFW, explicit, watermark etc).

It is really strange because sometimes I am able to gen 3-4 couples in a row, really separating them (like girl with red hair, undercut, guy with black long hair) and it works relatively consistent. They even interact, wrap arms together, look at each other and so on, until it doesn't and I have to reroll 4 or even sometimes 10 times where it always gens just 1girl or merges both  together into 1 character (like half of the body is covered in a suit jacket or one leg has a pants on). It's really random and I have not found what to do about it. I tried to set the areas with a gap in between, without a gap, even overlapping sections, doesn't change the random behavior.

Would be really nice if we could like weight the prompts, as said, that bird, moon, sun, planet in the background maybe not that important, I could inpaint it.

**Comment by Haoming02** [comment]
> Typing 33 for 33% is much easier than 0.33

Doing so would require me to divide every single value by `100` afterwards, which I would rather not do. Just click on the right side of the field, press `backspace` until there is only `0.` left, then type the `33` to get the `0.33` :P

> I sometimes need to reroll a lot

Well yeah... this Extension isn't 100% guarentee. It's still just a "suggestion." Also, the composition is dependent on the Checkpoint as well. If the model doesn't understand what you mean, it will not be able to generate it even with this Extension.

> I select "last" as global but it still would tell that there "numbers of couples and mapping is not the same". I then need to go to advanced and add another layer

This... seems to be the reason that is causing the 2nd issue for you. The **Global Effect** *(`Background`)* is **NOT** available in the `Advanced` mode. So perhaps you have been using it wrong, and the Extension wasn't taking effect to being with?

> Would be cool if we had a reload button that reads the prompt and generates layers from the \n in the input.

It already automatically populates the prompt fields for both `Advanced` and `Mask` mode. So if you don't see a layer or see an empty field, that means the Extension will not work in the current configuration.

**Comment by Haoming02** [comment]
As for "adding weight to the prompts," pretty sure the Webui built-in emphasis *(**ie.** `(` , `)` , `[`, `]` )* still works per layer, in addition to the weights for the entire layer from this Extension.

**Comment by maniac-0s** [comment]
Thanks for the hint with the 33, didn't know that. Had to try that for all the other fields that are 0.0-1.0 ranges in all of Forge.

I also already thought about setting whole prompt layers into brackets with weights didn't experiment with that yet tho.

Although I think the problem with the inconsistency was maybe a bit of a a misunderstanding on my part. I thought I can just prompt the layers and everything that's global in the last or first line. However it seems I ALSO have to tell the model again, that I want multiple people.

So the extension works more consistent if I always include "couple", "group", "multiple people" or something similar, best in the global prompt, otherwise it is pure luck when the model actually creates a more than 1girl/guy.

I thought about it this way: The prompts are like generating separate latent images that then in the last steps and the VAE are fused together into one, but setting live preview to 2 steps you see that sometimes people appear and disappear shortly after in the earliest steps, like the network decides to fuse them together into one person.

As for the update, yes but sometimes that doesn't work right. In advanced I sometimes have to select default mapping and then add the other layers manually by clicking into the last one and adding one row below.

**Comment by Haoming02** [comment]
> the extension works more consistent if I always include "couple", "group", "multiple people"

Yes, that is mentioned in the first line of [How to Use](https://github.com/Haoming02/sd-forge-couple?tab=readme-ov-file#how-to-use)

> add the other layers manually 

Yes, the Extension only syncs the prompts. It will **not** add/remove layers on its own.

**Comment by maniac-0s** [comment]
>Yes, the Extension only syncs the prompts. It will not add/remove layers on its own.

However where this is a bit of a problem is when I send something img2img. When I have 3 layers, 2 person and one global, I always have to reset it with "default mapping" button mode and then add the third layer to it. Then I have to type in the numbers again or drag the box around to match the whole picture.
Worse it is when I have more than 3 layers then I have to set up all layers manually again.

**Comment by Haoming02** [comment]
> when I send something img2img

This is also mentioned in the [README](https://github.com/Haoming02/sd-forge-couple?tab=readme-ov-file#advanced-mode) for `Advanced Mode`:

> **Note:** The mapping data is not sent when using the `Send to img2img` function. Click the `Pull from txt2img` to manually transfer the data. *(vice versa)*
