### ISSUE TITLE
Extension has no effect despite installed

### ISSUE THREAD

**Issue by giteeeeee** [Haoming02/sd-forge-couple#6]
I'm using webui forge, the most recent commit.

I've installed the extension using git clone:

![2024-03-29 145920](https://github.com/Haoming02/sd-forge-couple/assets/89521447/99ad61c4-a3dc-40a0-9320-930761e5be68)

prompt:

![2024-03-29 144130](https://github.com/Haoming02/sd-forge-couple/assets/89521447/9782cda6-e084-40a5-8b2b-35bdad953989)

No error in console.

Output:

![00274-animagineXLV31_v31, 357671229327](https://github.com/Haoming02/sd-forge-couple/assets/89521447/6aec1d04-fad3-4770-95ab-ed0cc20495b2)

Then I deleted the extension, restarting webui. Using the same prompt:

![00275-animagineXLV31_v31, 357671229327](https://github.com/Haoming02/sd-forge-couple/assets/89521447/37a1b374-5f71-40c9-bda7-1de1843754ca)

Getting the same image.

So I don't think the extension had hooked up to my webui previously.

**Comment by Haoming02** [comment]
Did you enable it?

**Comment by giteeeeee** [comment]
> Did you enable it?

Do you mean:

![2024-03-29 145920](https://github.com/Haoming02/sd-forge-couple/assets/89521447/b67f036a-ffc7-4b61-bdce-d8b22a570930)

Ticking the box? Yes, it's ticked.

**Comment by Haoming02** [comment]
Under the parameters, like other Extensions...

**Comment by giteeeeee** [comment]
> Under the parameters, like other Extensions...

oops

Guess I'm not yet used to how forge present its plugins xd

![00281-animagineXLV31_v31, 357671229327](https://github.com/Haoming02/sd-forge-couple/assets/89521447/1de24bd6-267f-42f9-a5c1-ee3d325922fe)

Thanks. Awesome extension!
