### ISSUE TITLE
A couple issues with advanced mode and custom separators

### ISSUE THREAD

**Issue by jamesjimmy88** [Haoming02/sd-forge-couple#60]
Hello; I usually use several line breaks in my prompts to keep things more organized, so I use a custom word as couple separator (FCPL in this case) - something like this:
_quality tags, 
lora 1, 
lora 2, 
lora 3, 
FCPL
1girl, 
dress, accessory, 
position
FCPL
1boy,
dress, accessory, 
position
FCPL
window_

The first issue is that using advanced mode (more precisely after you deselect one of its prompt fields) will make the line breaks immediately before and after the custom separators disappear, so the above prompt would become something like this:
_quality tags,
lora 1, 
lora 2, 
lora 3,FCPL1girl, 
dress, accessory, 
positionFCPL1boy,
dress, accessory, 
positionFCPLwindow_
Which can become quite unreadable

The second issue with custom separators and advanced mode is that activating it after the prompt was written can outright remove chunks of it. To reproduce, follow these steps:
- in a new webui window copy-paste the prompt at the top in your positive prompt window
- enable Forge Couple
- enable advanced mode
- type FCPL in the Couple separator field
- add a row in the advanced mode window or click and deselect one of the prompt fields (both work)
- Check the prompt, which is now just this:
_quality tags,FCPLlora 1,FCPL1boy,
dress, accessory, 
positionFCPLwindow_
As you can see, an entire section got completely removed.

Thank you.

**Comment by maniac-0s** [comment]
I didn't try it yet with your separator but someone commenting on my issue suggested to use two \n
https://github.com/Haoming02/sd-forge-couple/issues/58#issuecomment-2343261944
So in your case it would be \nFCPL\n

Because you have a \n after every line.

**Comment by jamesjimmy88** [comment]
The extra `\n`s are a nice idea, thanks.
> As for the second issue, I can only suggest that you prompt on only one side
That's what I usually do, but even then going back and forth between the prompt and the extension doesn't trigger this issue if it already happened, as it only happens once after you change the separator to a custom one; the main problem is that there's no way to avoid it other than setting up Forge Couple beforehand (as even adding a row will trigger it).

**Comment by Haoming02** [comment]
Hmm, I'll see if I can cook up a way to check if the `separator` has changed, then adjust accordingly before the sync.

Though, that will have to wait til tomorrow. ~~My brain ain't braining rn~~

**Comment by jamesjimmy88** [comment]
Not sure if it's worth it to open another issue just for this (if you want this in a separate issue just say so), but I've been using \nFCPL\n as suggested, and while that info is stored in the images' metadata, importing them back via the PNG info tab doesn't import the '\n's from the field, just the 'FCPL' part.

**Comment by Haoming02** [comment]
Hello, pushed a new commit that should ~~hopefully~~ fix all issues mentioned!
- Mention the trick to add `\n` before and after custom separator in the README
- Actively sync the separator
- Respect `\n` separator in infotext

**Comment by jamesjimmy88** [comment]
Thanks for the update, much appreciated.
Just a nitpick, but I assume is an easy fix: importing an image via the PNG info tab doesn't import `\n`s in the Couple Separator field.

**Comment by Haoming02** [comment]
Newly generated images should work now, while old ones will not work...

Cause before the update today, I used to strip the whitespaces *(which includes the newline)* from the separator. So the newlines were never saved in the infotext...

**Comment by jamesjimmy88** [comment]
Oh, you're right. It's fine then, no biggie. Thank you once again!
