### ISSUE TITLE
Does this not work in Highres Fix?

### ISSUE THREAD

**Issue by maniac-0s** [Haoming02/sd-forge-couple#61]
When I generate a couple and run Highres Fix over it, both faces become similar features, the man gets feminine eyes and the face expressions, that I fist made different, get equalized. Even with denoiser as low as 0.2. Same happens in tiled upscale on img2img. I guess that's an issue with tiles?

**Comment by Haoming02** [comment]
Eh... probably not gonna support `Hires. fix`, if it's not working that is. And if so, just do it in `img2img`, which I know does work.

As for `Tiling`, it was mentioned in #27 , which, frankly I have no idea how to fix either.

**Comment by maniac-0s** [comment]
Yeah I can imagine that this is quirky. 

Tiling is creating several 1mp images from the picture and then glues them together so you'd have to split up the couple space equally which means your extension would need to work together with the tiling script to know which areas are affected and then you'd need to apply that to the couple thing.

Very tricky.
