### ISSUE TITLE
Issues with Masking Feature + ControlNet (doesnt separate well)

### ISSUE THREAD

**Issue by queenofinvidia** [Haoming02/sd-forge-couple#63]
I'm trying to use the masking feature with a picture + controlnet but for some reason it doesn't separate the 2 different sides and just seems to break. Advanced mode seems to have slightly better results, but the whole reason I wanted to use the masking feature was to minimize the bleed by specifying regions really closely and tracing over them

Some examples..

note: both characters are part of the same LORA

Image #1: Masked with lora weights per character region (1st background, 2nd girl on right, 3rd boy on right. the hair colors merge)
![image](https://github.com/user-attachments/assets/c2ea1d1e-cb5e-4925-ab46-9c8aad85c0b8)

Image #2: Masked with lora weights applied to all regions (1st background + 1.0 lora weights, 2nd girl, 3rd boy)
![image](https://github.com/user-attachments/assets/0cd4f2c6-398c-4915-aaa9-cf306821cd55)

Image #3: Advanced Mode Only (lora weights applied to all regions)
![image](https://github.com/user-attachments/assets/87328891-d0e3-41c3-9eb4-726bb336c89c)

Image #4 Advanced Mode Only (Lora weights applied per character region)
![image](https://github.com/user-attachments/assets/937e24d6-42f9-4247-b687-0ed842c11678)

Image #5 ControlNet settings - I used same settings for every picture here
![image](https://github.com/user-attachments/assets/5e1d69ee-e45a-4c38-9ce8-ddf789ef3ae0)

now, this could ENTIRELY be my error but I'm not sure.

I just found it strange that the results in masking mode, which are supposed to be more precise, are worse than just cutting the regions in half, so I thought it could be an issue and I wanted to report it.

If I am doing something wrong please let me know. I love to improve and learn.

Thank you for all your help!

EDIT:

I decided to try the masking feature again without any controlnet and I notice I still have the same issue.

(mask mode)
![image](https://github.com/user-attachments/assets/c11d3b55-8797-40f5-92ab-8d36c95f72bd)

(advanced mode)
![image](https://github.com/user-attachments/assets/46adb3b6-13bd-4722-87c7-7a2298e200e6)

just trying to supply as much info as possible in case masked mode is bugged.

**Comment by Haoming02** [comment]
The Masks should be binary *(**ie.** Only black & white)*

But yours all look gray, so they probably are not doing much.

How were you creating the masks?

**Comment by queenofinvidia** [comment]
I got it working now after some playing around. Thank you for your answer. I don't remember how I got gray masks honestly LOL but I figured out the problem.

**How I fixed it**
1. I had to turn on global effect - first line 
2. When I was drawing the masks I didn't realize that the mask for character 1, after I saved it, remained on the canvas which led to it still being present when I was drawing the mask for character 2, and so they combined
![image](https://github.com/user-attachments/assets/b5a6d48f-d04f-4e4f-bf61-4ec0720cbb79)

so I then figured out I had to reset the canvas, draw the mask for character 2, and then override the one that had both characters on the canvas. (Now I know you can just hit Reset to clear the first mask and draw the 2nd mask but I didn't know that at first lol)

![image](https://github.com/user-attachments/assets/194d4f07-e071-429b-8a4d-da5ff8605b1c)
(it works!!!)

I thought I would write how I fixed it here in case someone else runs into this problem. I'm so glad the feature works great!

I only have one suggestion, and that would be after clicking "Save Mask" if the canvas would automatically move to another layer so when you draw another mask, it wouldnt combine with the previously drawn mask. 

I know now you can hit Reset to clear the 1st mask but I thought it might be slightly better if it "reset the canvas" after hitting save mask instead. either way, I know how to do it now and I am so glad!

Thank you for always being so helpful Haoming! You do awesome work for us <3 I'll leave this open in case you want to reply.

Appreciate how you always answer my posts! ^_^
