### ISSUE TITLE
Mask Canvas Shrinking

### ISSUE THREAD

**Issue by antareskyo** [Haoming02/sd-forge-couple#64]
https://github.com/user-attachments/assets/e343f982-75a9-4607-8661-24eedac5940d

Most of the time the canvas will keep shrinking, and creating an empty canvas will have the same result, there's no error output and I don't have any plugins that affect the canvas.

**Comment by Haoming02** [comment]
Huh, interesting...

Do you have Extensions that modify the `width` and `height` sliders? And can you try other browsers as well?

**Comment by antareskyo** [comment]
I forgot to mention that I'm running this on reForge, which was the actual source of the problem.
It works completely fine on Forge proper but sometimes it does work in reForge, don't know if the dev branch has better chances of success.
