### ISSUE TITLE
Feature request: Common prompt

### ISSUE THREAD

**Issue by Natans8** [Haoming02/sd-forge-couple#66]
Not so long ago I switched over from [Regional Prompter](https://github.com/hako-mikan/sd-webui-regional-prompter) and one of the features I've been missing the most is the common prompt.

This is how it looked:

> If this option enabled, first part of the prompt is added to all region parts.
>  
> 
> ```
> best quality, 20yo lady in garden BREAK
> green hair twintail BREAK
> red blouse BREAK
> blue skirt
> ```
> 
> 
> If common is enabled, this prompt is converted to the following:
> 
> 
> ```
> best quality, 20yo lady in garden, green hair twintail BREAK
> best quality, 20yo lady in garden, red blouse BREAK
> best quality, 20yo lady in garden, blue skirt
> ```

It was very convenient in a way that I could add common tokens without having to tinker with their weight like in the base prompt (global effect).
Currently I overcome this by copying the common prompt I want to every single line, but I believe it would be very convenient to add the option to do so automatically, and having a choice similar to the global effect where the common line would be positioned.

**Comment by Haoming02** [comment]
Please check out the latest commit~

**Comment by Natans8** [comment]
I want to kiss you on the mouth right now

**Comment by Haoming02** [comment]
~~monkaS~~

**Comment by Haoming02** [comment]
Actually, I'mma rewrite this feature.

Doesn't feel as useful as I imagined it to be...

**Comment by Haoming02** [comment]
Hello, please check out the new implementation
