### ISSUE TITLE
Output is black rectangle

### ISSUE THREAD

**Issue by GretaThuumberg** [Haoming02/sd-forge-couple#69]
Worked for the first few generations, then afterwards all generations were a black rectangle.

Retraced back my steps, changed to basic mode, no change. Anything generated with this extension activated is a black screen now.

**Comment by Haoming02** [comment]
I find it unlikely to be caused by this Extension.

Do you have any errors in the Console?

**Comment by GretaThuumberg** [comment]
Not sure if I can call it an answer, but somehow got rid of it by removing the entire prompt and generating with just a few words. Then I manually re-input the prompt and it still worked.

No idea what could've caused it, maybe something I did tuning the prompts messed with the separation code.
