### ISSUE TITLE
I still have issues with couples

### ISSUE THREAD

**Issue by maniac-0s** [Haoming02/sd-forge-couple#72]
The problem is, that I always have to tell it in a general line (like first or last) to actually generate two people, or state that in every line otherwise it is just generating one in the center.

So what I do (generally, not the actual prompt but similar) is:

Prompt:

```
1guy/man, wearing something, doing ...
1girl/woman etc, wearing something, doing ...
couple, girl and guy, location prompt, other background or concept things
```
Settings:

Enable forge couple and use advanced and set the boxes accordingly, making sure the third layer is spanning the entire picture and one layer is left one is right. Still many of the times I generate just 1 person in center. With couple in third line it works better however then they are always couple posing like hugging etc, which I don't always want.

Sometimes when SD thinks something fits more to a girl than a guy (like long hair for instance) it puts the girl in 1st half of the image and creates a guy where the girl should be. I try to use weights but then often I get 1girl in the center.

Is there a fool-proof way to make sure, that it always generates two people, even if it's like 8 out of 10? Its very often hit and miss (depending on the model it misses very often, Pony finetunes seen to get it right more often (but then it often has NSFW touch) while SDXL have a harder time of giving desired results).

Also when I try 1guy between two girls, I have difficulties figuring out what to put in third line. 1guy and 2girls often just generates two girls or again just 1 person in center.

**Comment by Haoming02** [comment]
> I always have to tell it in a general line (like first or last) to actually generate two people, or state that in every line, otherwise it is just generating one in the center.

Yes, this is mentioned in the **README**

> when SD thinks something fits more to a girl than a guy (like long hair for instance) it puts the girl in 1st half of the image and creates a guy where the girl should be

Depends on how flexible the Checkpoint is I guess. If the checkpoint is too biased, this Extension wouldn't be able to override it.

In the following example, I have to additionally add the clothing for it to generate in the correct side. Otherwise, it will indeed always put the girl in the side with `long hair`...

<p align="center">
<img src="https://github.com/user-attachments/assets/ec3bf940-b1d9-421d-9157-fbc5bf1760e9">
</p>

```
a woman and a man, black dress, short hair,
a man and a woman, white suit, long hair,
[high quality, best quality], a cinematic photo of a couple
```

- Generated with `realvisxlV50`
