### ISSUE TITLE
Common prompt syntax dose nothing

### ISSUE THREAD

**Issue by wrathgoddess** [Haoming02/sd-forge-couple#73]
turning on or off syntax doesn't result in a different image 
![Screenshot 2024-11-06 085529](https://github.com/user-attachments/assets/a05833eb-1ef1-495d-96a1-3fcd227888d3)
 testing example prompt: score_9, score_8_up, score_7_up, source_anime, high quality, best quality, masterpiece, {subject:2girls}, 
{subject}, murano sayaka, low twintails, {cloth:brown dress, white sailor collar, neckerchief, standing, arms behind back, looking at viewer, smile, blush, classroom}, 
{subject}, hinoshita kaho, medium hair, {cloth}, 
![26938-3346443452-score_9, score_8_up, score_7_up, source_anime, high quality, best quality, masterpiece, subject_2girls, _subject, murano sayaka,](https://github.com/user-attachments/assets/23652424-9990-4900-b5fb-dad72ce11fb8)
![Screenshot 2024-11-06 085848](https://github.com/user-attachments/assets/bfdb034a-9e96-44a3-bea9-9cbe2592f852)
same results 
![26938-3346443452-score_9, score_8_up, score_7_up, source_anime, high quality, best quality, masterpiece, subject_2girls, _subject, murano sayaka,](https://github.com/user-attachments/assets/15832b52-d763-451d-9f61-110d0c9a97f8)

debug:
[Forge Couple] Common Prompts Applied:
score_9, score_8_up, score_7_up, source_anime, high quality, best quality, masterpiece, subject:2girls,
subject, murano sayaka, low twintails, cloth:brown dress, white sailor collar, neckerchief, standing, arms behind back, looking at viewer, smile, blush, classroom,
subject, hinoshita kaho, medium hair, cloth,

**Comment by Haoming02** [comment]
Do you have other Extensions that process prompt?

**eg.** [sd-dynamic-prompts](https://github.com/adieyal/sd-dynamic-prompts) ?

**Comment by wrathgoddess** [comment]
yah i do have that extension so just disable it in extension list and it should work ?

**Comment by Haoming02** [comment]
Does [dynamic-prompts](https://github.com/adieyal/sd-dynamic-prompts) use `< >` as well?

**Comment by wrathgoddess** [comment]
it would seem so when testing i also tried the other syntax option with same result. and thank you disabling the extension worked maybe adding this to a list of conflicting extensions would be a big help for others 
NEW RESULT: 
![26949-3346443452-score_9, score_8_up, score_7_up, source_anime, high quality, best quality, masterpiece, {subject_2girls}, _{subject}, murano say](https://github.com/user-attachments/assets/751dc904-f2b0-4d08-8d08-06af752b6776)
