### ISSUE TITLE
Broken if Lobe Theme is enabled

### ISSUE THREAD

**Issue by ostap667inbox** [Haoming02/sd-forge-couple#74]
Forge Couple does not work if the [Lobe Theme](https://github.com/lobehub/sd-webui-lobe-theme) extension is enabled in Forge. Blocks are not visible on canvas. 
![forge-couple](https://github.com/user-attachments/assets/3634ee5c-1e26-42d9-957e-fa48d660e8b5)
Some time ago the extensions were compatible and could work together. If it possible, see if there is a way to maintain compatibility. Lobe Theme improves usability, many users use it. Thanks!

**Comment by Haoming02** [comment]
Yeah nah... I'm not gonna bother.

Half of my elements are just straight up deleted by it. Very cool.
