### ISSUE TITLE
A way to save region assignments 

### ISSUE THREAD

**Issue by wrathgoddess** [Haoming02/sd-forge-couple#75]
it would be cool if there was a way to save / load region assignments settings for the advance mode
![Screenshot 2024-11-13 054320](https://github.com/user-attachments/assets/f8d51d2d-cdf0-4bf4-b11e-117c2a4b89be)
 may be simpler to implement something that save a file with setting in it you can load like this
![Screenshot 2024-11-13 054754](https://github.com/user-attachments/assets/c96b6642-c466-4c0d-979a-c99a65ba4079)
 or a way to save the setting on to the saved image 
![tmpa1tgehzk](https://github.com/user-attachments/assets/ef09cafd-7775-4b39-b81b-93e21116a7c3)
 so you don't have to try and realign everything when trying to remake an image. 
not sure if its possible but food for thought.

**Comment by Haoming02** [comment]
Added~

**Comment by Haoming02** [comment]
> a way to save the setting on to the saved image

btw, the mapping is indeed saved to the infotext

**Comment by wrathgoddess** [comment]
ik its saved to the image created i was talking about the saved grid image but not that important, thanks for the quick work with the presets gonna save a lot of time for people
