### ISSUE TITLE
Masked mode causes severe lag.

### ISSUE THREAD

**Issue by PaleKemono** [Haoming02/sd-forge-couple#76]
The extension works great, but if i try and open "mask" region assignment mode the webui page starts lagging until it freezes. The canvas opens and the brush starts decreasing in size and moves towards the left side by it's own.
I don't have any issues with inpainting or other extensions, this only happens with this one for some reason.
Im using the "main" branch of ReForge.

**Comment by PaleKemono** [comment]
[issue.webm](https://github.com/user-attachments/assets/4929736e-4a86-4d06-9f0e-ac6659ba2ad5)

**Comment by Haoming02** [comment]
See #65
