### ISSUE TITLE
Mask mode does not work properly

### ISSUE THREAD

**Issue by benfy95** [Haoming02/sd-forge-couple#78]
Just updated both Forge and Extension to the latest current version and the mask mode does not work. Basic prompt works well.

Getting errors during mask mode, and the objects I want it to be at specific mask does not work. (It just igores the mask I have drawn)

And I misconfigured something or?

`*** Error running after_extra_networks_activate: D:\AI\stable-diffusion-webui-forge\webui\extensions\sd-forge-couple\scripts\forge_couple.py
    Traceback (most recent call last):
      File "D:\AI\stable-diffusion-webui-forge\webui\modules\scripts.py", line 876, in after_extra_networks_activate
        script.after_extra_networks_activate(p, *script_args, **kwargs)
      File "D:\AI\stable-diffusion-webui-forge\webui\extensions\sd-forge-couple\scripts\forge_couple.py", line 110, in after_extra_networks_activate
        assert isinstance(mapping[0], dict)
    AssertionError`

![Screenshot 2024-11-22 121411](https://github.com/user-attachments/assets/0c0c0c19-4515-4fe8-9220-733fbfe35441)
![Screenshot 2024-11-22 121429](https://github.com/user-attachments/assets/0d71ff7b-e5af-429a-8ca2-5cb639766ee7)

Result
![00036-464467553](https://github.com/user-attachments/assets/d46ba464-5a2d-4b54-8ba5-16324f3bf50d)

**Comment by Haoming02** [comment]
Do you have `--api` on?

**Comment by benfy95** [comment]
> Do you have `--api` on?

Yes, should I turn it off? 

---

Let me turn it off and try again.

**Comment by Haoming02** [comment]
It's mentioned in the **README**...

https://github.com/Haoming02/sd-forge-couple#api

**Comment by benfy95** [comment]
> It's mentioned in the **README**...
> 
> https://github.com/Haoming02/sd-forge-couple#api

Thanks, because I just carried forward my previous installation, apparently after removing --api still having errors, right now I removed all other arguments and kept only --xformers and it is now working correctly without any errors.

**Comment by Nziner** [comment]
Same error. --api flag disabled. Basic prompt works well.
*** Error running after_extra_networks_activate: D:\Work\AI\StableDiffusion\webui_forge\webui\extensions\sd-forge-couple\scripts\forge_couple.py
    Traceback (most recent call last):
      File "D:\Work\AI\StableDiffusion\webui_forge\webui\modules\scripts.py", line 876, in after_extra_networks_activate
        script.after_extra_networks_activate(p, *script_args, **kwargs)
      File "D:\Work\AI\StableDiffusion\webui_forge\webui\extensions\sd-forge-couple\scripts\forge_couple.py", line 112, in after_extra_networks_activate
        assert isinstance(mapping[0], dict)
    AssertionError

---
