### ISSUE TITLE
Mask contains non-filled areas

### ISSUE THREAD

**Issue by inkling211** [Haoming02/sd-forge-couple#82]
give this error Mask contains non-filled areas , and make black image

**Comment by Haoming02** [comment]
Well... fill the mask then?

**Comment by inkling211** [comment]
> Well... fill the mask then?

make nothing 
![tmpd1giprgd](https://github.com/user-attachments/assets/c6f0ab79-f962-4e26-8625-1e5779127afe)

**Comment by Haoming02** [comment]
Cause... it's not filled?

Read the **README** please

**Comment by inkling211** [comment]
> Cause... it's not filled?
> 
> Read the **README** please

cant find can you explain ?

**Comment by Haoming02** [comment]
https://github.com/Haoming02/sd-forge-couple#mask-mode

**Comment by Haoming02** [comment]
<p align="center">
<img src="https://github.com/user-attachments/assets/5630232a-e421-44dd-91d3-463000af2b5b">
</p>

**Comment by inkling211** [comment]
> ![](https://private-user-images.githubusercontent.com/73768377/398691558-5630232a-e421-44dd-91d3-463000af2b5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDQ3NTYsIm5iZiI6MTczNTIwNDQ1NiwicGF0aCI6Ii83Mzc2ODM3Ny8zOTg2OTE1NTgtNTYzMDIzMmEtZTQyMS00NGRkLTkxZDMtNDYzMDAwYWYyYjViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDA5MTQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YmY0ZWRmOWVmOTA4MmVhMWYzZGZmZGY2MjBmMzBlN2RiODkzMmQ0OGU4OTliOTJlNGVlMjRmMDE4NDdlYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rwONPAAJq0qaxdRfkVUjhOuLrjBvkxdCfRDiBIr9SzM)

fixed thanks
