### ISSUE TITLE
is it work on epic realism xl?

### ISSUE THREAD

**Issue by inkling211** [Haoming02/sd-forge-couple#83]
i tried and make just one cracter.
lora:score_9, score_8_up,score_7_up,
a Slow cooker mimic with large teeth<lora:mimics-sdxl-prod-e:1>
a toaster mimic with large teeth

first line is global 
![00038-389679333](https://github.com/user-attachments/assets/61ec4de8-c4d1-4d41-ae6f-8dab96745a42)
 image result

**Comment by Haoming02** [comment]
Your prompt makes no sense to me

**Comment by inkling211** [comment]
> Your prompt makes no sense to me

first line is global and this 2 other line are 2 mimic (from dark souls ) but just give the line2 , and turned into anime

**Comment by Haoming02** [comment]
Why do you type the LoRA like that? Did they even activate?

Also, why are you using Pony tags on a Realistic checkpoint that is not based on Pony anyway...
