### ISSUE TITLE
Minor UI bug with advanced region assignment number fields on Firefox

### ISSUE THREAD

**Issue by pronor121** [Haoming02/sd-forge-couple#9]
Using Firefox, when editing the input fields on the region assignment mapping, hitting enter clears the inputs instead of saving them. Clicking anywhere outside the highlighted field saves it as expected. Previewing the mapping confirmed the fields are blank, and not just visually. I've also replicated this on a blank profile with no extensions.

EDIT: also happens with tab

Hitting enter works as expected in Edge.

Commit: 89acc89
Browser: Firefox 124.0.1
OS: Windows 10

**Comment by Haoming02** [comment]
Welp... that's on Gradio. I don't think I would be able to fix it.

**Comment by pronor121** [comment]
Sounds about right for Gradio. Thanks for having a look
